#!/usr/bin/env bash

if [[ -x "$(command -v rye)" ]]; then
  export RYE_HOME="${HOME}/Development/sdks/rye"
  export UV_LINK_MODE=copy
  export RYE_NO_AUTO_INSTALL=1
fi  
#: https://pipenv.pypa.io/en/latest/
if type "pipenv" > /dev/null; then
    export PIPENV_CACHE_DIR=$HOME/Development/.cache/pipenv
    export PIP_CACHE_DIR=$HOME/Development/.cache/pip
fi

#: load virtualenv
export WORKON_HOME=$HOME/Development/.virtualenvs
export PROJECT_HOME=$HOME/Development/projects/python

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"

if [[ -x "$(command -v pyenv)" ]]; then
    eval "$(pyenv init -)"
fi
