return {
  symlink = '',
  arrows = {
    ArrowRight = "❯",
    ArrowLeft = "❮",
    -- ChevronRight = "",
    ChevronRight = ">",
    CurvedArrowRight = " ",
    DoubleArrowRight = "»",
    SmallArrowRight = "➜",
    Diamond = "<>",
  },
  folder = {
    arrow_open = '',
    arrow_closed = '',
    default = '',
    open = '',
    empty = '',
    empty_open = '',
    symlink = '',
    symlink_open = '',
  },
  ui = {
    BigCircle = " ",
    BigUnfilledCircle = " ",
    BookMark = " ",
    Bug = " ",
    Calendar = " ",
    Check = " ",
    Circle = " ",
    Close = " ",
    Code = " ",
    Comment = " ",
    Dashboard = " ",
    Fire = " ",
    Gear = " ",
    History = " ",
    Lightbulb = " ",
    List = " ",
    Lock = " ",
    NewFile = " ",
    Note = " ",
    Package = " ",
    Pencil = " ",
    Plus = "+",
    Project = " ",
    RunningMan = "🏃",
    Search = " ",
    SignIn = " ",
    Table = " ",
    Telescope = " ",
    Yoga = "🧘",
    Xmark = "✗",
  },
  diagnostics = {
    BoldError = "",
    BoldHint = "",
    BoldInformation = "",
    BoldQuestion = "",
    BoldWarning = "",
    Debug = "",
    Error = " ",
    Hint = " ",
    Information = "",
    Question = "",
    Trace = "✎",
    Warning = "",
  },
  git = {
    Add = " ",
    Diff = " ",
    Ignore = " ",
    Mod = " ",
    Remove = " ",
    Rename = " ",
    Repo = " ",
  },
  git_state = {
    unstaged = '✗',
    staged = '✓',
    unmerged = '',
    renamed = '➜',
    untracked = '★',
    deleted = '',
    ignored = '◌',
  }
}
