#!/usr/bin/bash

NC="\e[0m" # No Color
BLACK="\e[30m"
BLUE="\e[34m"
BROWN="\e[33m"
CYAN="\e[36m"
DARKGRAY="\e[30m"
GREEN="\e[32m"
LIGHTBLUE="\e[34m"
LIGHTCYAN="\e[36m"
LIGHTGRAY="\e[37m"
LIGHTGREEN="\e[32m"
LIGHTPURPLE="\e[35m"
LIGHTRED="\e[31m"
PURPLE="\e[35m"
RED="\e[31m"
WHITE="\e[37m"
YELLOW="\e[33m"


BOLD="\e[1m"
NORMAL=$(tput sgr0)