[tools]
bun = "latest"
node = "latest"
go = "1.22.0"
zigmod = "r89"
zig = "0.11.0"
uv = "latest"
exa = "latest"

[settings]
always_keep_download = false    # deleted after install by default
always_keep_install = true      # deleted on failure by default
jobs = 4
not_found_auto_install = true
paranoid = false                # see https://mise.jdx.dev/paranoid.html
env_file = '.env'
activate_aggressive = true
asdf_compat = true # set to true to ensure .tool-versions will be compatible with asdf, see `MISE_ASDF_COMPAT`
