[tools]
bun = "latest"
node = "latest"

[settings]
always_keep_download = false
always_keep_install = false

jobs = 4
not_found_auto_install = true
paranoid = false
env_file = '.env'

activate_aggressive = true

