[tools]
atuin = "18.17.1"
bat = "latest"
buf = "1.71.0"
bun = "latest"
chezmoi = "2"
cosign = "3.1.1"
dua = "latest"
foundry = "latest"
fzf = "0.74.0"
gh = "2.96.0"
gitleaks = "8.30.1"
glab = "1.108.0"
go = "latest"
helm = "4.2.3"
httpie-go = "0.7.0"
just = "1"
neovim = "0.12.4"
node = "26.5.0"
opentofu = "latest"
pre-commit = "4.6.0"
python = "3.14.6"
ripgrep = "15.2.0"
rust = "1.97.1"
rye = "latest"
sccache = "0.16.0"
shellcheck = "latest"
shfmt = "latest"
terragrunt = "latest"
usage = "latest"
uv = "0.11.29"
yamllint = "1.38.0"
zellij = "0.44.3"
zig = "latest"
zoxide = "0.10.0"

"aqua:awscli" = "2.36.2"
"aqua:derailed/k9s" = "latest"
"aqua:getsops/sops" = "3.13.2"
"aqua:gohugoio/hugo/hugo-extended" = "0.164.0"
"cargo:eva" = "0.3"
"cargo:eza" = "0.23.4"
"npm:biome" = "0.3.3"
"npm:socket" = "1.1.143"
"starship" = "latest"
tmux = "latest"
lazygit = "0.63.1"
sqlite = "3.53.3"
codex = "latest"
task = "3.52.0"
gcloud = "576.0.0"
glow = "2.1.2"


[plugins]

[settings]
always_keep_download = false             # deleted after install by default
always_keep_install = false              # deleted on failure by default
jobs = 8
not_found_auto_install = true
paranoid = true                          # see https://mise.jdx.dev/paranoid.html
env_file = '.env'
activate_aggressive = false
asdf_compat = true                       # set to true to ensure .tool-versions will be compatible with asdf, see `MISE_ASDF_COMPAT`
http_timeout = '10'                      # set the timeout for http requests in seconds, see `MISE_HTTP_TIMEOUT`
experimental = true
idiomatic_version_file_enable_tools = []
