[tools]
"cargo:eza" = "latest"
"starship" = "latest"
bat = "latest"
bun = "latest"
go = "latest"
just = "1"
node = "26.1.0"
opentofu = "latest"
rye = "latest"
shellcheck = "latest"
shfmt = "latest"
usage = "3.3.0"
uv = "latest"
zig = "0.16.0"
"cargo:eva" = "0"
"aqua:awscli" = "2"
chezmoi = "2"
"aqua:terrastruct/tala" = "latest"
"aqua:terrastruct/d2" = "latest"
"npm:socket" = "1"
k9s = "latest"
foundry = "1"
"npm:@mermaid-js/mermaid-cli" = "latest"
zellij = "latest"
fzf = "latest"
markdownlint-cli2 = "latest"
github-markdown-toc = "latest"
"github:atanunq/viu" = "1.6.1"
atuin = "18.16.1"
sops = "3.13.1"
hugo-extended = "0.161.1"
pre-commit = "4.6.0"
act = "0.2.88"
codex = "0.134.0"
caddy = "latest"
fx = "39.2.0"
"npm:@tobilu/qmd" = "2.1.0"
"github:asciinema/asciinema" = "3.2.0"
"github:asciinema/agg" = "1.8.1"
argocd = "3.4.2"
age = "1.3.1"
zoxide = "0.9.9"
dotnet-core = "10.0.300"
"github:houseabsolute/precious" = "0.10.2"
opencode = "1.15.13"
"github:charmbracelet/crush" = "0.76.0"
"github:k1LoW/mo" = "1.5.5"
"npm:defuddle" = "0.18.1"

[settings]
always_keep_download = false             # deleted after install by default
always_keep_install = false               # deleted on failure by default
jobs = 4
not_found_auto_install = true
paranoid = false                         # see https://mise.jdx.dev/paranoid.html
env_file = '.env'
activate_aggressive = false
asdf_compat = true                       # set to true to ensure .tool-versions will be compatible with asdf, see `MISE_ASDF_COMPAT`
http_timeout = '10'                      # set the timeout for http requests in seconds, see `MISE_HTTP_TIMEOUT`
experimental = true
idiomatic_version_file_enable_tools = []
lockfile = true

[settings.npm]
package_manager = "bun"
