[tools]
"aqua:derailed/k9s" = "latest"
"cargo:eza" = "latest"
"starship" = "latest"
"ubi:houseabsolute/precious" = "latest"
"ubi" = "latest"
bat = "latest"
bun = "latest"
go = "latest"
java = "11"
just = "1"
maven = "3"
node = "20"
opentofu = "latest"
rye = "latest"
shellcheck = "latest"
shfmt = "latest"
usage = "latest"
uv = "latest"
zig = "0.14.0"
"aqua:foundry-rs/foundry" = "latest"
"aqua:atuinsh/atuin" = "latest"
"aqua:gohugoio/hugo/hugo-extended" = "0.147.2"
rust = "1.87.0"
"aqua:getsops/sops" = "3.10.2"
"cargo:eva" = "0.3"
"npm:@anthropic-ai/claude-code" = "1.0.38"
"aqua:awscli" = "2"
chezmoi = "2"
"ubi:opencontainers/umoci" = "latest"
act = "0.2.78"
"aqua:terrastruct/tala" = "0.4.2"
"aqua:terrastruct/d2" = "0.7.0"
terragrunt = "0.81.7"
"npm:socket" = "1.0.0"

[settings]
always_keep_download = false             # deleted after install by default
always_keep_install = true               # deleted on failure by default
jobs = 4
not_found_auto_install = true
paranoid = false                         # see https://mise.jdx.dev/paranoid.html
env_file = '.env'
activate_aggressive = false
asdf_compat = true                       # set to true to ensure .tool-versions will be compatible with asdf, see `MISE_ASDF_COMPAT`
http_timeout = '10'                      # set the timeout for http requests in seconds, see `MISE_HTTP_TIMEOUT`
experimental = true
idiomatic_version_file_enable_tools = []
