[tools]
"ubi" = "latest"
act = "0.2.78"
atuin = "18.10.0"
bat = "latest"
buf = "1.57.2"
bun = "latest"
chezmoi = "2"
cosign = "2.5.2"
dua = "latest"
flyctl = "0.3.172"
foundry = "latest"
fzf = "0.64.0"
gh = "2.76.1"
gitleaks = "8.28.0"
glab = "1.74.0"
go = "latest"
helm = "3.17.4"
httpie-go = "0.7.0"
just = "1"
neovim = "0.11.2"
node = "25.3.0"
opentofu = "latest"
pre-commit = "4.3.0"
python = "3.12.11"
redis-cli = "8.2-m01"
ripgrep = "14.1.1"
rust = "1.90.0"
rye = "latest"
sccache = "0.10.0"
shellcheck = "latest"
shfmt = "latest"
terragrunt = "latest"
usage = "latest"
uv = "0.9.21"
yamllint = "1.37.1"
zellij = "0.43.1"
zig = "0.14.0"
zoxide = "0.9.8"

"aqua:awscli" = "2.27.47"
"aqua:derailed/k9s" = "latest"
"aqua:getsops/sops" = "3.10.2"
"aqua:gohugoio/hugo/hugo-extended" = "0.147.2"
"aqua:terrastruct/d2" = "0.7.0"
"aqua:terrastruct/tala" = "0.4.2"
"cargo:eva" = "0.3"
"cargo:eza" = "0.21.4"
"npm:aws-cdk" = "2.1024.0"
"npm:biome" = "0.3.3"
"npm:socket" = "1.0.0"
"pipx:glances" = { version = "4.3.2", action = "", containers = "", graph = "", ip = "", sensors = "", wifi = "" }
"pipx:SuperClaude" = "4.1.4"
"starship" = "latest"
"ubi:charmbracelet/crush" = "0.32.1"
"ubi:grafana/alloy" = "latest"
"ubi:houseabsolute/precious" = "latest"
"ubi:tsenart/vegeta" = "12.13.0"
"ubi:steveyegge/beads" ={ exe = "bd", version = "latest"}
tmux = "3.6a"
lazygit = "0.59.0"
sqlite = "3.52.0"
codex = "0.114.0"
task = "3.44.1"
gcloud = "565.0.0"


[settings]
always_keep_download = false             # deleted after install by default
always_keep_install = false               # deleted on failure by default
jobs = 4
not_found_auto_install = true
paranoid = false                         # see https://mise.jdx.dev/paranoid.html
env_file = '.env'
activate_aggressive = false
asdf_compat = true                       # set to true to ensure .tool-versions will be compatible with asdf, see `MISE_ASDF_COMPAT`
http_timeout = '10'                      # set the timeout for http requests in seconds, see `MISE_HTTP_TIMEOUT`
experimental = true
idiomatic_version_file_enable_tools = []
